### numpy 기본

In [1]:
import numpy
from pprint import pprint

In [2]:
arr1 = numpy.array([2,3,5,7,11,13,31])

In [3]:
arr1

array([ 2,  3,  5,  7, 11, 13, 31])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(7,)

In [6]:
arr2 = numpy.array([[1,2,3,4],[33,44,55,4],[2,22,33,3]])

In [7]:
arr2

array([[ 1,  2,  3,  4],
       [33, 44, 55,  4],
       [ 2, 22, 33,  3]])

In [8]:
arr2.shape

(3, 4)

shape 모양을 알려줌

In [9]:
arr2.size

12

요소를 알려줌

## numpy `arange`

In [10]:
import numpy as np

In [11]:
arr = np.arange(1,101)

In [12]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [13]:
arr = np.arange(3,101,3)
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

### numpy 리스트 인덱싱, 슬라이싱

In [14]:
arr1[-1]

31

In [15]:
arr1

array([ 2,  3,  5,  7, 11, 13, 31])

In [16]:
arr[[1,2,5]]

array([ 6,  9, 18])

`arr[[1,2,4]]` 형태는 리스트 안의 리스트는 인덱스 번호와 같은 애들만 갖고온다.

In [17]:
a2=[1,2,4]
arr[a2]

array([ 6,  9, 15])

인덱싱도 가능하고 슬라이싱도 가능


In [18]:
arr[1:10:2]

array([ 6, 12, 18, 24, 30])

### numpy  기본연산

In [27]:
arr1 = np.arange(10)
arr2 = np.arange(10,20)
pprint(arr1)
pprint(arr2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


In [21]:
arr1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
arr1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [24]:
arr1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

arr1 을 프린트 해도 값은 변하지 않는다.  
```
arr1 = arr1 * 2
```
이런식으로 해야함

In [28]:
arr1 + arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#### 연습 문제

In [33]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.
won_array = np.array(revenue_in_yen)
won_array = won_array * 10.08
# 정답 출력
won_array

array([3024000., 3427200., 3225600., 3628800., 4435200., 1411200.,
       1814400., 3427200., 3326400., 2923200., 2822400., 3830400.,
       1713600., 1411200., 2318400., 3931200., 4032000., 3528000.,
       3830400., 1512000., 1108800., 2419200., 3830400., 3830400.,
       3427200., 4233600., 1512000., 1310400., 3628800., 3225600.,
       2520000.])

#### 연습문제 2

In [38]:

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

# 코드를 작성하세요.
won_array = np.array(revenue_in_yen)*10.08 + np.array(revenue_in_dollar)*1138

# 정답 출력
won_array

array([4389600., 5248000., 4818800., 5108200., 6825000., 3004400.,
       3521400., 5817000., 5033400., 4630200., 5439800., 6220200.,
       4900000., 4370000., 4253000., 5524400., 6421800., 6145400.,
       5651200., 3560400., 3612400., 5150400., 6220200., 7016800.,
       5589400., 6623400., 3560400., 3814000., 6018600., 5046400.,
       4568400.])

### numpy boolean

In [39]:
arr1 = np.arange(10)
arr1>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [40]:
arr1 %2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [45]:
boolean = arr1%2==0
boolean

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [57]:
boolean = arr1>3
np.where(boolean)

(array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

`np.where`참인 애들만 나오게 해줌 --인덱스만 나온다.

In [58]:
#이를 이용하면 
arr1 *= 2
filtering=np.where(boolean)
arr1[filtering]

array([ 8, 12, 16, 20, 24, 28, 32, 36])

#### 연습문제 3

In [69]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.
r = np.array(revenue_in_yen)
f = np.where(r<200000)
bad_days_revenue=r[f]

# 다른 방법 
# yen_array = np.array(revenue_in_yen)
# bad_days_revenue = yen_array[yen_array < 200000]

# 정답 출력
bad_days_revenue

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])